apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: vault-platform
  description: Platform team maintaining Vault self-service modules and workflows.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf:
    - vault-platform
