#!/usr/bin/env node
/*
 * generate.mjs — Vault Self-Service Portal catalog/docs generator.
 *
 * For each Terraform module it:
 *   1. Runs `terraform-docs` to extract inputs/outputs (machine-readable).
 *   2. Writes an inline TechDocs site under idp/docs/<module>/ (mkdocs.yml +
 *      docs/index.md) sourced from the module README + a generated
 *      inputs/outputs reference, so the Docs tab renders without drift.
 *   3. Writes a variable inventory to idp/generated/variables/<module>.json.
 *
 * Requires: terraform-docs on PATH. Run via `make generate`.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const idpRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(idpRoot);

// module name -> source directory (relative to repo root)
const MODULES = {
  'terraform-vault-cluster-onboarding': 'terraform-vault-onboarding/terraform-vault-cluster-onboarding',
  'terraform-vault-gitlab-onboarding': 'terraform-vault-onboarding/terraform-vault-gitlab-onboarding',
  'terraform-vault-add-k8s-namespace-access': 'terraform-vault-onboarding/terraform-vault-add-k8s-namespace-access',
  'terraform-vault-add-gitlab-project-access': 'terraform-vault-onboarding/terraform-vault-add-gitlab-project-access',
  'terraform-vault-add-kvv2': 'terraform-vault-onboarding/terraform-vault-add-kvv2',
  'terraform-vault-add-pgsql-role': 'terraform-vault-onboarding/terraform-vault-add-pgsql-role',
  'terraform-vault-add-permission-group': 'terraform-vault-onboarding/terraform-vault-add-permission-group',
  'terraform-vault-pgsql-onboarding': 'terraform-vault-onboarding/terraform-vault-pgsql-onboarding',
  'terraform-vault-hcptf-onboarding': 'hcp-vault-base-setup/terraform-vault-hcptf-onboarding',
};

function tfDocs(format, dir) {
  return execFileSync('terraform-docs', [format, dir], {
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  });
}

let count = 0;
for (const [name, rel] of Object.entries(MODULES)) {
  const srcDir = join(repoRoot, rel);
  if (!existsSync(srcDir)) {
    console.warn(`SKIP ${name}: source dir not found at ${srcDir}`);
    continue;
  }

  // 1. machine-readable inventory
  const json = JSON.parse(tfDocs('json', srcDir));
  const inventory = {
    module: name,
    inputs: (json.inputs ?? []).map(i => ({
      name: i.name,
      type: i.type,
      required: i.required,
      default: i.default,
      description: i.description,
    })),
    outputs: (json.outputs ?? []).map(o => ({
      name: o.name,
      description: o.description,
    })),
  };
  const invDir = join(idpRoot, 'generated', 'variables');
  mkdirSync(invDir, { recursive: true });
  writeFileSync(join(invDir, `${name}.json`), `${JSON.stringify(inventory, null, 2)}\n`);

  // 2. inline TechDocs
  const md = tfDocs('markdown', srcDir);
  const readmePath = join(srcDir, 'README.md');
  const readme = existsSync(readmePath) ? readFileSync(readmePath, 'utf8') : `# ${name}\n`;

  const docsDir = join(idpRoot, 'docs', name, 'docs');
  mkdirSync(docsDir, { recursive: true });

  const indexMd = `${readme.trimEnd()}\n\n---\n\n` +
    `## Terraform reference (generated)\n\n` +
    `_Generated by \`make generate\` from \`${rel}\`. Do not edit by hand._\n\n` +
    `${md.trimEnd()}\n`;
  writeFileSync(join(docsDir, 'index.md'), indexMd);

  const mkdocs = `site_name: ${name}\n` +
    `site_description: Vault self-service Terraform module\n` +
    `plugins:\n  - techdocs-core\n` +
    `nav:\n  - Overview: index.md\n`;
  writeFileSync(join(idpRoot, 'docs', name, 'mkdocs.yml'), mkdocs);

  count += 1;
  console.log(`generated docs + inventory for ${name}`);
}

console.log(`\nDone. ${count} modules processed.`);
