name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: idp

jobs:
  ci:
    name: Lint, Typecheck, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: idp/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn tsc:full

      - name: Lint
        run: yarn lint:all

      - name: Test
        run: yarn test:all
